server:
  port: 8082
spring:
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: NJ
ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: product-center #为哪些服务的名称开启饥饿加载,多个用逗号分隔
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
#    root: debug
    com.fly.study.usercenter.feign.config: debug
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: false